name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest

    steps:
      - name: Set up V (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v
          cd /tmp/v
          ./make.bat

      - name: Set up V
        if: matrix.os != 'windows-latest'
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v
          cd /tmp/v
          make

      - name: Set up PATH (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "D:/tmp/v" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set up PATH
        if: matrix.os != 'windows-latest'
        run: |
          echo "PATH=/tmp/v:${PATH}" >> "$GITHUB_ENV"

      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the project (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          v -shared .

      - name: Build the project
        if: matrix.os != 'windows-latest'
        run: |
          make
          test -f problemdetail.so && rm problemdetail.so

      - name: Test the project
        run: |
          v test .
