name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Set up V
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v
          cd /tmp/v
          make
          echo "PATH=${PWD}:${PATH}" >> "$GITHUB_ENV"

      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the project
        run: |
          make
          test -f problemdetail.so && rm problemdetail.so

      - name: Test the project
        run: |
          v test .
